version: "2"
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,module"
      standard: "Drupal"
    checks:
      Drupal NamingConventions ValidVariableName LowerCamelName:
        enabled: false
      Drupal Commenting InlineComment SpacingAfter:
        enabled: false
